#!/usr/bin/env bash

#  Created by Marko Justinek on 30/8/24.
#  Copyright © 2024 Marko Justinek. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Properties
NEW_VERSION="$1"
CHANGELOG="CHANGELOG.md"
CHANGELOG_OLD="$CHANGELOG.old"
CHANGELOG_CURRENT="CHANGELOG.current"

# Get the latest existing tag
CURRENT_VERSION=$(git describe --tags --match "[0-9].*" --abbrev=0 HEAD)

# Backup the existing CHANGELOG.md
if [ -f "$CHANGELOG" ]; then
    mv "$CHANGELOG" "$CHANGELOG_OLD"
else
    echo "File '$CHANGELOG' does not exist. Creating one now..."
    touch "$CHANGELOG_OLD"
fi

# Save changes since last tag into a file
git log --pretty='* %h - %s (%an)' "${CURRENT_VERSION}"..HEAD >> $CHANGELOG_CURRENT

# Add title for the release
echo "## ${CURRENT_VERSION} - ${NEW_VERSION}" > "$CHANGELOG"

# Save the list of commits/changes into changelog
cat $CHANGELOG_CURRENT | cat - "$CHANGELOG_OLD" > "$CHANGELOG"

# Clean up
rm "$CHANGELOG_OLD"
