name: ":: release"

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "♻️ Checkout"
        uses: actions/checkout@v4

      - name: "🏷  Release version ${{ inputs.release-version }}"
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          body_path: $${{ github.workspace }}/CHANGELOG.current
          generate_release_notes: true
          append_body: true

